#! /bin/sh

# Key combination
sxhkd &

bspc monitor ^1 -d 1 2 3
bspc monitor ^2 -d 4 5 6 7
bspc monitor ^3 -d 8 9 0

bspc config border_width 0
bspc config window_gap 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle true # Smart gaps

~/.config/flashfocus/launch.sh &
~/.config/polybar/launch.sh &
~/.config/compton/launch.sh &
~/.config/redshift/launch.sh &
~/.config/nvidia-led/launch.sh &
~/.config/feh/launch.sh &
