#!/bin/bash

SINKID=0

if [[ $(hostname -s) = "host" ]]; then
    SINKID=1
fi

case $1 in --increase)
        ponymix increase 1
        # pactl set-sink-volume $SINKID +1%
        ;;
    --decrease)
        ponymix decrease 1
        # pactl set-sink-volume $SINKID -1%
        ;;
    --toggle)
        echo "toggle"
        ponymix toggle
        # pactl set-sink-mute $SINKID toggle
        ;;
esac


